### ISSUE TITLE
dataframe writeCSV adds blank line

### ISSUE THREAD

**Issue by lynnjo** [Kotlin/dataframe#106]
Whenever I output a csv, a blank line is always written at the top of the file.  This happens whether I"m creating a dataframe from a list of objects, or if I read a csv file into a dataFrame, process it in some manner, and then write it back out.  I always get a blank line as the first line.  Is this intentional?  How to prevent?

I am running a gradle project, using dataframe:0.8.0-dev-952
I have also seen this with the rc-7 load.

Easiest way to reproduce:
1.  Read any comma-separated file into a dataframe,
2.  Write the dataframe out to another file

val inputFile = <path to file>
val myDF = DataFrame.readCSV(inputFile)

val outputFile = <different file to write>
myDf.writeCSV(outputFile

**Comment by koperagen** [comment]
Hi! Thank you for the report. I don't think it's intentional, most likely it's a bug, I'll look into it tomorrow. For now, i can suggest using `df.toCsv` to get String, then remove leading characters and write it to a file.

**Comment by koperagen** [comment]
Resolved in new published version `0.8.0-rc-8`
