### ISSUE TITLE
Possible to read csv to nested data class hierarchy?

### ISSUE THREAD

**Issue by ionox0** [Kotlin/dataframe#114]
Is it possible to have something like this:
```
data class Parent(
  val child: Child
)

data class Child(
  val age: Int
)

val df = DataFrame
        .readCSV(inputCsv)
        .convertTo<Parent>()
```

Maybe there is some way to specify how the fields are nested using the `headers = ` parameter?

**Comment by koperagen** [comment]
Hi! I would split the problem into two parts:
1. Read CSV into a dataframe with nested hierarchy. Here we have two options: 
    i) read flat CSV and use https://kotlin.github.io/dataframe/group.html to create nesting.
    ii) if cells of your CSV contain JSON values, then dataframe will read them into `ColumnGroup` (value is object) or `FrameColumn` (value is array of objects). It's not mentioned in the current version of the documentation, i will publish an update :)
2. Get a list of a data class instances from the dataframe with nested hierarchy: https://kotlin.github.io/dataframe/collectionsinterop.html#interop-with-data-classes

**Comment by alwyn** [comment]
@koperagen 

"If cells of your CSV contain JSON values, then dataframe will read them into ColumnGroup or FrameColumn"

Is there a way to disable this because it is not standard CSV behaviour and it is currently messing up in my case by interpreting [ ] as a nested dataframe.

**Comment by koperagen** [comment]
> [@koperagen](https://github.com/koperagen)
> 
> "If cells of your CSV contain JSON values, then dataframe will read them into ColumnGroup or FrameColumn"
> 
> Is there a way to disable this because it is not standard CSV behaviour and it is currently messing up in my case by interpreting [ ] as a nested dataframe.

Yes, using colTypes parameter. For example: `DataFrame.readCSV(.., colTypes = mapOf("myCol" to ColType.String))`
