### ISSUE TITLE
Multiply two columns and save to another column

### ISSUE THREAD

**Issue by PoslavskySV** [Kotlin/dataframe#116]
Hi guys,

thank you for great library. May be I just can't find this in docs (sorry if that is the case), but how I can e.g. multiply two columns or take a square root? 
I have two columns with double values `count1` and `count2` and I want to do

```kotlin
df.map { count1 * count2 into "mul" }
// and
df.map { sqrt(count1 * count2) into "geomMean" }
```

The only thing I can do is to multiply on a fixed number
```kotlin
df.map { count1 * 2 into "smth" }
```

Thanks

**Comment by nikitinas** [comment]
Hi!

Currently only a limited set of column-wise operations are supported., but you can use `from` infix function to create columns from any row-wise expression:

```kotlin
df.map {
  "mul" from { count1 * count2 }
  "geomMean" from { sqrt(count1*count2) }
}
```

**Comment by PoslavskySV** [comment]
Super, thank you! This is exactly what I was looking for.
