### ISSUE TITLE
Type converter from kotlinx.datetime.Instant to java.time.Instant is not found

### ISSUE THREAD

**Issue by n3gbx** [Kotlin/dataframe#126]
Given I have a csv file with the following columns and values:
```
date,description,notes
2022-07-07T19:53:15.009Z,Some description, Some notes
```
And kotlin data class:
```
import java.time.Instant

data class Record(
    val date: Instant,
    val description: String,
    val notes: String,
)
```
It throws an error: 
```
org.jetbrains.kotlinx.dataframe.exceptions.TypeConverterNotFoundException: Type converter from kotlinx.datetime.Instant to java.time.Instant is not found
```
When I read the csv:
```
DataFrame.readCSV("data.csv").convertTo<Record>()
```

How can I make it working if I don't want to use kotlinx.datetime?

**Comment by koperagen** [comment]
Hi! Thank you for the report. First of all, it's a bug. It makes total sense to have automatic conversion from kotlinx Instant to java Instant :) I'll fix it. As a workaround you can use ConvertSchemaDsl, but you need to import kotlinx.datetime.Instant for it to compile:

```
df.convertTo<Record> {
            convert<Instant>().with { it.toJavaInstant() }
}
```

**Comment by koperagen** [comment]
Version with a fix `0.8.1-dev-1064`

**Comment by gilbertojrequena** [comment]
Hey @koperagen I have a question, why the PRs or commits are not related to their issues?

**Comment by gilbertojrequena** [comment]
Yes, I think that mentioning the issue # in the commit message would be sufficient. Thanks. And sorry for bringing a topic not related to the issue.
