### ISSUE TITLE
Version alignment for plugin org.jetbrains.kotlin.plugin.dataframe?

### ISSUE THREAD

**Issue by jmfayard** [Kotlin/dataframe#128]
Bonjour,

I'm currently [adding support for Kotlinx.dataframe.*](https://github.com/jmfayard/refreshVersions/pull/559) in [refreshVersions](https://jmfayard.github.io/refreshVersions/)

But I stumbled upon this issue when I tried to use the plugin:

> Plugin [id: 'org.jetbrains.kotlin.plugin.dataframe', version: '1.7.0'] was not found in any of the following sources: gradlePluginPortal(), mavenCentral()

The thing is that until now all Gradle plugins `id("org.jetbrains.kotlin.*")` had a version aligned with the version of Kotlin.

The ones that weren't were in the KotlinX namespace like `id("org.jetbrains.kotlinx.benchmark")`

So we hardcoded a rule for plugins in the `org.jetbrains.kotlin` namespace. And we are probably not the only ones.

I understand that you have not released a stable version yet.

Question: do you plan to align the stable versions of your plugin with the version of Kotlin?

If yes, all fine.

If no, would it be too late to use the kotlinx namespace instead?

**Comment by koperagen** [comment]
Hi! I'll discuss with the team and let you know

**Comment by koperagen** [comment]
I'll move the plugin in `kotlinx` namespace next week

**Comment by jmfayard** [comment]
Awesome thanks 👍

Le jeu. 14 juil. 2022 à 13:32, Nikita Klimenko ***@***.***> a
écrit :

**Comment by koperagen** [comment]
Hi! I moved the plugin to "org.jetbrains.kotlinx.dataframe", please try out a new version "0.8.1" :) library is also updated to "0.8.1"
