### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by jbaron** [Kotlin/dataframe#130]
when running the following code the first time in a cell in a Jupyter Lab notebook:

`%use dataframe(0.8.1)`

I get a the following exception:

`JupyterIntegration:WARNING => A resource with classpath 'table.css' not found.`

I have a custom exception handler installed, so not sure if it normally doesn't pop-up. 

When I run same  `%use dataframe(0.8.1)` again, there is no error anymore and also the table rendering afterwards looks better.

**Comment by koperagen** [comment]
Hi! What do you mean by a custom exception handler? What version of the Kotlin kernel? I couldn't reproduce this bug from the first try :(

**Comment by jbaron** [comment]
versions used :
===================
jupyter-client        7.0.6
jupyter-core          4.9.1
jupyter-server        1.11.2
jupyterlab            3.2.8
jupyterlab-pygments   0.1.2
jupyterlab-server     2.8.2
kotlin-jupyter-kernel 0.11.0.95

**Comment by jbaron** [comment]
I also checked a bit more my code and it is not the custom exception handler `addThrowableRenderer(....)` but rather the logging module. I see WARNING level errors in my output cell, but you should see it where ever you log the WARNINGS.

**Comment by jbaron** [comment]
Hereby also two screenshots of the same table, once rendered after running the `%use dataframe(0.8.1)` the first time and once after running it for a second time. Clearly the CSS for the table is different.

![Screenshot-first](https://user-images.githubusercontent.com/568564/180776511-008b49d9-9972-4170-8714-582b05325d27.png)
![Screenshot-second](https://user-images.githubusercontent.com/568564/180776517-4d0af84f-c836-4106-9fe1-220c481d3f53.png)

**Comment by zaleslaw** [comment]
@jbaron could you please check, is it reproduced on dataframe (0.10.0) or not if you have a time?
It will be helpful for us.

**Comment by jbaron** [comment]
@zaleslaw So long ago, forgot all about this issue :) 

But I can confirm that with dataframe 0.10.0 I don't get this error anymore. So this issue can be closed.

**Comment by zaleslaw** [comment]
Yes, sorry for the long delay with answering your question.
Thanks for the confirming.
Hope in the future we will not keep issues without reaction for too long.

Have a good day!
