### ISSUE TITLE
DataFrame<T>.append(vararg values: Any?) does not fail on incorrect arguments passed

### ISSUE THREAD

**Issue by sulevsky** [Kotlin/dataframe#131]
If an invalid number of arguments are passed to DataFrame.append then the assertion is not checked (by default is turned off) and unchanged DataFrame is returned (which is a bit misguiding)
1. Create  a DataFrame with 2 columns
2. Call `append` with a single parameter

Ex.
```
 dataFrameOf("name", "age")(
        "Alice", 15,
        "Bob", 20)
        .append("John")
```

Expected: exception or updated DataFrame

**Comment by koperagen** [comment]
Hi! Thank you for the report and pointing that 'assert' is turned off by default.

**Comment by koperagen** [comment]
Hi! It should now throw an exception on `0.9.0-dev-1079
