### ISSUE TITLE
ReadExcel data with headers not on row 1

### ISSUE THREAD

**Issue by Burtan** [Kotlin/dataframe#132]
Hey,
how to read excel tables that don't have their headers on the first row? Many scientific applications export their data with printing device information into the first rows and then following with the actual data.

**Comment by koperagen** [comment]
Hi! `readExcel` API doesn't support this right now. Would `skipRows: Int = 0` parameter work for you? For `skipRows = 1` it'll read headers from the second row.

**Comment by koperagen** [comment]
Btw, what application do you use? Would be interesting to better understand the use cases :)

**Comment by Burtan** [comment]
A skipRows function would help. It's qPCR data from a thermo scientific machine. I'm testing some code to automate data evaluation in a pathology context.

**Comment by koperagen** [comment]
Hi! Try `0.9.0-dev-1079` with the fix

**Comment by Burtan** [comment]
Hey, 
it now correctly skips the given rows, but only takes the columns which are also present in the first row. Here is an example of my sheet. It now only reads Well and Well Position as headers.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\fb\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\fb\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Block Type | 96-Well 0.2-mL   Block |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Calibration Background is expired | No |   |   |   |   |   |   |  
...
Stage/ Cycle where Ct Analysis is   performed | Stage1, Step1 |   |   |   |   |   |  
User Name |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
Well | Well Position | Omit | Sample Name | Target Name | Task | Reporter | Quencher | CT



</body>

</html>

**Comment by koperagen** [comment]
Oh, i see. You can specify column range as a workaround for now. `readExcel(columns = "A:H")` Meanwhile, ill commit the fix and hopefully it'll be published soon :)

**Comment by Burtan** [comment]
Thanks, this works!

**Comment by Burtan** [comment]
I think the first row after the header is skipped?

**Comment by koperagen** [comment]
> I think the first row after the header is skipped?

Can't reproduce in a test. Can you send a minified example + code that reads it?

**Comment by Burtan** [comment]
Please try this project. The link expires after 7 days. Thanks!
https://cloud.frederik-bertling.de/f/6ebb5bb52031407f9809/

**Comment by koperagen** [comment]
Hi! I'm not sure what's going on, but i can't even read this file. Also, when i open it in google sheets / libreoffice calc, i see this: 
![image](https://user-images.githubusercontent.com/12936457/183893453-f0f1a9b7-0646-443d-8aa8-71997b688c7d.png)

Is it expected?

**Comment by Burtan** [comment]
I can confirm, it works now. Thanks!
