### ISSUE TITLE
Some examples issues

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#134]
Idea-examples: 
- movies does not contain a csv in the resources (nor the resources folder)
- titanic `System.setProperty("user.dir", System.getProperty("user.dir") + "/examples/idea-examples/titanic")` doesn't seem to do anything on my device (Arch linux), so the path resolution gets it wrong
- youtube needs to be updated of course :)

Jupyter:
- movies again doesn't have a csv
- netflix some plotting issues
-  puzzles, `age.isNaN()` needs to be `age().isNaN()`, seems like `DataColumn<Double>.isNaN()` doesn't exist (anymore), same for `animal == "cat"`, `age in 0.0..10.0`... am I missing something? 
Edit: Ah this only works in jupyter, was trying to reproduce it in normal intellij, they need to be generated... )
- the rest works fine :)

**Comment by koperagen** [comment]
I vaguely remember that `movies.csv` is left out in purpose due to licensing issues. There is a chance that it's mentioned in jupyter notebook somewhere. But yeah, it's not at all obvious :)

**Comment by Jolanrensen** [comment]
> I vaguely remember that `movies.csv` is left out in purpose due to licensing issues. There is a chance that it's mentioned in jupyter notebook somewhere. But yeah, it's not at all obvious :)

We could probably come up with some fake movie names :)

**Comment by Jolanrensen** [comment]
[movies.csv](https://github.com/Kotlin/dataframe/files/9252679/movies.csv)
maybe something like this? Or do you want some more years to be the same? (Yeah I had too much fun with this)

**Comment by koperagen** [comment]
Wow. I think it'll work. If someone wants actual data, one can download a dataset  https://github.com/Kotlin/dataframe/blob/master/examples/jupyter-notebooks/movies/movies.ipynb.

**Comment by Jolanrensen** [comment]
I'll update the notebooks in Datalore and then close this issue as well :)
