### ISSUE TITLE
NPE when using not null KProperty to update data with nulls

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#136]
So this code
```kotlin
@DataSchema
interface Schema {
    val i: Int
}

val df = dataFrameOf("i")(1, null)

df.fillNulls(Schema::i).with { 42 }
```
causes java.lang.NullPointerException
More generic example (fillNulls uses update): 
`df.update(Schema::i).with { 42 }`.

`fillNulls` can avoid throwing exception. Not sure what to do about `update`. Maybe more meaningful error message

**Comment by Jolanrensen** [comment]
I think this makes sense. `fillNulls()` with a reference to a non-null column makes sense to fail. Unfortunately, I don't think Kotlin has a way to mark an abstract type as "must be nullable".
In your example, you only want to use the name "i" and if you want to be safe using `Schema::i.name` works fine.

**Comment by koperagen** [comment]
> `fillNulls()` with a reference to a non-null column makes sense to fail

why? if there are no nulls, just do nothing :)  
it throws exception because in implementation update is called, and it tries to prodive previous value (which is null, but non-null type is expected).

**Comment by Jolanrensen** [comment]
maybe we could make `fillNulls()` return a `Update<T, C?>` instead? So, weaken the type to be nullable even if the column isn't.
