### ISSUE TITLE
can't convert column to toLocalDateTime with format

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/dataframe#144]
I miss this function:
```kotlin
df.convert("date_time").toLocalDateTime("yyyy-MM-dd'T'HH:mm:ss'Z'")
```

**Comment by koperagen** [comment]
Hi! Do you have a sample of code that parses String to LocalDateDate using this format?

**Comment by devcrocod** [comment]
```kotlin
val json = """{
    "name": "Petr",
    "date": "2000-13-21T15:27:49Z"
}"""

val df = DataFrame.readJsonStr(json)
```
then I try to convert a type of date to LocalDateTime using String API and I can convert with default local but can't with my local:

```kotlin
df.convert("date").toLocalDateTime() // works fine

df.convert("date").toLocalDateTime("yyyy-MM-dd'T'HH:mm:ss'Z'") // missing toLocalDateTime fun
```

**Comment by zaleslaw** [comment]
@Jolanrensen please check

**Comment by Jolanrensen** [comment]
This is intentional. The function you're looking for is defined like:
```kotlin
public fun <T, R : String?> Convert<T, R>.toLocalDateTime(
    pattern: String? = null,
    locale: Locale? = null,
): DataFrame<T> = to { it.convertToLocalDateTime(pattern, locale) }
```
and thus can only be called on `String`-typed columns, not `Any` columns. This means that this does work:
```kotlin
df.convert { "date"<String>() }.toLocalDateTime("yyyy-MM-dd'T'HH:mm:ss'Z'")
```
I don't think it's wise to open this up to columns of any type.

**Comment by zaleslaw** [comment]
Probably close, if won't fix?

**Comment by Jolanrensen** [comment]
@zaleslaw if we all agree :) 
@koperagen what do you think?

**Comment by devcrocod** [comment]
@Jolanrensen 
Will this also work for <String?>?

**Comment by Jolanrensen** [comment]
> ```kotlin
> public fun <T, R : String?> Convert<T, R>.toLocalDateTime(
> ```

I'd imagine yes, because of:

`public fun <T, R : String?> Convert<T, R>.toLocalDateTime(`
