### ISSUE TITLE
the dataframe can display when the notebook is first time loaded, but after the notebook page refresh, the notebook can not display

### ISSUE THREAD

**Issue by zhangliangbo** [Kotlin/dataframe#151]
Uncaught ReferenceError: call_DataFrame is not defined
<img width="554" alt="image" src="https://user-images.githubusercontent.com/14359338/184789346-d920e623-9669-434b-baf9-1d6f0134cf63.png">
just a summary without data

**Comment by Jolanrensen** [comment]
Are you running the notebook in trusted mode?

**Comment by zhangliangbo** [comment]
> 



> Are you running the notebook in trusted mode?

it works, thanks a lot
