### ISSUE TITLE
Schema to generated DataSchemas fails for large file

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#185]
Generating types using either the KSP or Gradle plugin from the following json file results in the error shown in the picture. (it should be 12, not 6)
Good luck!

![image](https://user-images.githubusercontent.com/17594275/200848852-c93b828e-9c31-4380-9f69-2d6048a72334.png)
[ApiGuruSample.zip](https://github.com/Kotlin/dataframe/files/9971685/ApiGuruSample.zip)

**Comment by ermolenkodev** [comment]
@Jolanrensen is the issue still present? I am asking because I saw something related to ApiCodeGuru in the code

**Comment by Jolanrensen** [comment]
No! Seems to be fixed :) I think your multi-staged data schema generation did it :)
