### ISSUE TITLE
It's not clear when you need to update Kotlin kernel in your env

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#208]
https://github.com/Kotlin/dataframe/commit/3db46ccccaa1291c0627307d64133317f545e6ae
This commit introduces breaking change in Jupyter integration, so dev version of dataframe starting with 1194 don't work with kernel versions < 0.11.0-180
Exception that's thrown when importing dataframe is not at all clear 
![image](https://user-images.githubusercontent.com/12936457/207312741-8c99ae3d-d5d9-48f8-993f-70ae075a154b.png)

So we need to find a way to tell people to update their kernel and to be aware of such changes ourselves

**Comment by Jolanrensen** [comment]
Library version 0.11.0-198 will allow setting a minKernelVersion inside the Integration class. We should probably set that before the 0.9.0 release :)
