### ISSUE TITLE
Failed to load library integration class 'org.jetbrains.kotlinx.dataframe.jupyter.Integration' java.lang.IllegalStateException: Only zero or one argument is allowed for library class org.jetbrains.kotlinx.jupyter.exceptions.ReplException: Failed to load library integration class 'org.jetbrains.kotlinx.dataframe.jupyter.Integration'

### ISSUE THREAD

**Issue by zhangliangbo** [Kotlin/dataframe#217]
![image](https://user-images.githubusercontent.com/14359338/210921215-b4db2867-42f6-4995-bed7-4422bf3048da.png)

**Comment by zhangliangbo** [comment]
version 0.9.1

**Comment by Jolanrensen** [comment]
I suspect you have a too-old Kotlin Jupyter kernel: https://github.com/Kotlin/kotlin-jupyter#updating

**Comment by zaleslaw** [comment]
@zhangliangbo was your issue solved with updating the kernel? Could we close this issue as a solved one?

**Comment by anson-val** [comment]
Got this error in Datalore too, however I am unable to update the kernel on Datalore cloud machines

**Comment by anson-val** [comment]
> I suspect you have a too-old Kotlin Jupyter kernel: https://github.com/Kotlin/kotlin-jupyter#updating

You are right! Thank you.

**Comment by Jolanrensen** [comment]
> Got this error in Datalore too, however I am unable to update the kernel on Datalore cloud machines

https://github.com/Kotlin/kotlin-jupyter#datalore
