### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by Adriankhl** [Kotlin/dataframe#222]
The documentation website (https://kotlin.github.io/dataframe/overview.html) still shows version 0.8 and I think it should be updated.

I tried to do this myself (seems related to https://github.com/Kotlin/dataframe/blob/master/docs/StardustDocs/project.ihp) but I couldn't figure out how to generate the documentation. Running `./gradlew korro` gives an error:

```
Could not apply requested plugin [id: 'io.github.devcrocod.korro', version: '0.1.1-dev-29'] as it does not provide a plugin with id 'io.github.devcrocod.korro'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'io.github.devcrocod.korro' not found.
```

**Comment by pacher** [comment]
Same here. I tried googling stardust and stardustdocs with no result.
And I had to comment out korro in my local build because gradle could not find it.
Always wanted to ask about it on slack or so some day.

**Comment by koperagen** [comment]
Issue with korro is weirdly related to Gradle JVM. Build doesn't work with JDK 17 very well, so lowering Gradle JVM to 11 will make it work. 
I think we need to just update gradle wrapper to newer versions to resolve it. Can you please try to update Gradle in `gradle-wrapper.properties` to newer versions and see if it resolves the issue for JDK 17?
As for documentation versions, i would have to ask my team :D I don't know how to update it. Now docs are built from md files in StartdustDocs/topics via our CI/CD. Korro is an utility to embed code snipets from tests into *.md files

**Comment by koperagen** [comment]
Ok, apparently updating version in that ihp file is how it should be done https://github.com/Kotlin/dataframe/commit/4ff5d54f1bf30ea7011df22720710ec41b7aee81. I'll have to deploy docs from CI after that

**Comment by Adriankhl** [comment]
Updating gradle wrapper version does not help, and downgrading to JDK11 fixes the `korro` problem.

And I have created a PR to update the version number.

**Comment by pacher** [comment]
@koperagen gentle reminder
> to deploy docs from CI

This issue is closed, but the documentation website still shows version 0.8

Related #227
