### ISSUE TITLE
Build failing with Gradle JVM 17 

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#225]
If you try building project with JVM 17, you get an error
```
Could not apply requested plugin [id: 'io.github.devcrocod.korro', version: '0.1.1-dev-29'] as it does not provide a plugin with id 'io.github.devcrocod.korro'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'io.github.devcrocod.korro' not found.
```

Lowering JDK to 11, for example, resolves the issue.

**Comment by Jolanrensen** [comment]
Probably need to wait for korro to update?

**Comment by koperagen** [comment]
Hm.. It might be an issue with korro, but it's so confusing. Error that gradle gives seems 100% misleading, because how the same plugin works well with JVM 11 and doesn't with 17?

**Comment by Jolanrensen** [comment]
Could be several things. Spark breaks on Java 17 too for some reason. I think Java 17 changed a lot of critical stuff.

**Comment by zaleslaw** [comment]
Agree with @Jolanrensen it's not a bug in reality, but related to other kinds of issues (artifacts/releases/dependency management) or maybe to enhancements (supporting JDK 17 could be a good idea to put on the roadmap) 

I suppose that we need to write somewhere on the GitHub the table of tested environments (JDKs, Kotlin versions, OS versions).

**Comment by koperagen** [comment]
It was indeed incompatibility in Gradle plugin, resolved with korro update
