### ISSUE TITLE
Add changlog

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/dataframe#228]
It seems that the repo has yet no changelog. So it's very hard for users to track how the project is evolving and what new features are being added. Could a change-log be added?

**Comment by Jolanrensen** [comment]
We have an official blog post coming which took a bit longer than expected. That contains a gigantic changelog and I will probably also make a smaller version of that for a GitHub release.

**Comment by Jolanrensen** [comment]
https://github.com/Kotlin/dataframe/releases/tag/build-0.9.1

**Comment by holgerbrandl** [comment]
Impressive list! Thanks @Jolanrensen
