### ISSUE TITLE
Some tests in the SchemaGeneratorPluginTest are failed

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/dataframe#248]
Some tests are failed, then I run unit-tests on macOS with Java 11 and Community Edition IDEA

Just check the messages in the attached PDF with the test results
[Test Results — Tests in 'dataframe.plugins.dataframe-gradle-plugin.test'.pdf](https://github.com/Kotlin/dataframe/files/10547042/Test.Results.Tests.in.dataframe.plugins.dataframe-gradle-plugin.test.pdf)

<img width="1680" alt="Снимок экрана 2023-01-31 в 14 56 33" src="https://user-images.githubusercontent.com/1198621/215780143-cd4a2f5b-210e-4428-af8e-a1774ad45afc.png">

**Comment by Jolanrensen** [comment]
I suspect you have an old version of the plugin installed on your system. Maybe it helps to publish the plugins module to mavenLocal and then run the tests again.
We need to streamline this process for sure

**Comment by zaleslaw** [comment]
I will try it on both machines (MacOS and Windows) and post the results today or tomorrow

**Comment by koperagen** [comment]
> If you cannot build the plugins module because the :core module fails to build because the plugin is not installed
Do you remember how this happened? The one and only part of the build that is expected to fail if gradle plugin is not published into mavel local is `SchemaGeneratorPluginIntegrationTest` in `dataframe-gradle-plugin`. Also, normally it is published when you run the build becase "build" task depends on publish to maven local in that module. :core should not have any dependencies like that. It would be nice if we can define sequence of actions to reproduce your problem and make sure it's related

**Comment by zaleslaw** [comment]
Ok, I'll try to describe all steps from the beginning on my macOS machine, but it looks like I just downloaded the project, a few times updated the Gradle via pressing on circle in the Gradle panel and run all unit tests in the different modules step-by-step

**Comment by zaleslaw** [comment]
I'll close the issue, guys
All tests are green after the next simple steps:

- remove all duplicated Java SDK from the Project Preferences (for example, I have two different JDK 11)
- invalidate all caches and restart the application
- rebuild the project
<img width="1680" alt="Снимок экрана 2023-02-02 в 14 38 01" src="https://user-images.githubusercontent.com/1198621/216340271-bed2f2a9-1184-4776-a903-297ca5ac8951.png">
