### ISSUE TITLE
Annotation processing for code generating typed data frames

### ISSUE THREAD

**Issue by apatrida** [Kotlin/dataframe#25]
We should be able to use the `@DataSchema` or similar annotation outside of Jupyter to codegen name and type safe accessors on a dataframe.  Currently that is only available within Jupyter.

**Comment by nikitinas** [comment]
Thanks for request!
Yes, we plan to create Kotlin compiler plugin that will do codegen and track dataframe schema changes in those operations where it's possible to predict

**Comment by nikitinas** [comment]
Gradle plugin for dataframe now supports extension properties generation, check it out. 

https://kotlin.github.io/dataframe/gradle.html
