### ISSUE TITLE
`withValue(value)` consistency

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#253]
Some functions in the API have the option `withValue` such as `update { something }.withValue(value)` while other functions, such as `convert {}` say they have it in the docs, yet don't.

We need to either add `withValue` everywhere a `with` occurs or just remove `withValue` from the entire API since `with { value }` does the same thing.

**Comment by Jolanrensen** [comment]
Let's remove `withValue` from update (neat deprecation with ReplaceWith ofc)
and remove it everywhere in the docs

**Comment by koperagen** [comment]
Hm, i have concerns about deprecations of this method because we can break examples in notebooks (especially in datalore) and there is at least one screenshot of some code in docs

**Comment by Jolanrensen** [comment]
Well, we can change those right? Good to know but it doesn't seem like a showstopper :)

**Comment by Jolanrensen** [comment]
Aah wait, `Update.withValue` does have some use, namely keeping the type the same :) `with {}` allows the type to change

**Comment by Jolanrensen** [comment]
Btw `Update.asNullable` is fairly useless. All it does is cast `Update<T, C>` -> `Update<T, C?>`.
This is then only useful for `Update.withValue()` because it expects an exact type match. But we can just as easily allow withValue to change nullability or just make users use `with {}` since that allows all type/nullability changes.

**Comment by koperagen** [comment]
> Well, we can change those right? Good to know but it doesn't seem like a showstopper :)

Sure, just something to keep in mind 

Regarding nullability, if `with` indeed allows nullability change, then `asNullable` looks like a leftover. Maybe it wasn't always possible. I vaguely remember there were design discussions about it, but i don't remember the final decision. 
Also, apart from `withValue` we also have `withZero`, `withNull`.

**Comment by Jolanrensen** [comment]
Yes, I'm indifferent to keep or remove `withZero` and `withNull`. Could be a handy addition since it's less typing than `with { 0.0 }` especially if autocompleted. I see more use in those than `withValue(value)`

**Comment by nikitinas** [comment]
Originally `withValue` was added to support possible performance optimizations, for example when user fills a long column with a single constant value (#291 )

**Comment by zaleslaw** [comment]
@Jolanrensen please revisit this
