### ISSUE TITLE
[Bug] Disable logging of exceptions from Swagger Parser / Jackson

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#262]
The `io.swagger.parser.v3:swagger-parser` dependency uses `org.slf4j:slf4j-simple` which needs its logs to be disabled. 
The exception thrown in the build logs is purely visual and doesn't affect the code, but it's annoying nonetheless.

**Comment by zaleslaw** [comment]
I will try to solve this problem somehow, give me a chance

**Comment by Jolanrensen** [comment]
Need to check if this error message is gone after the bootstrap version is bumped to 0.10.0. It should be fixed then
