### ISSUE TITLE
`renameToCamelCase` for columns with names starting with capital letter should lowercase it

### ISSUE THREAD

**Issue by belovrv** [Kotlin/dataframe#302]

**Comment by zaleslaw** [comment]
@belovrv what kind of CamelCase do you want?
- CamelCase?
- camelCase? (style lowerCamelCase)

For now, we have no documentation for this function, please give some examples of usage or share some insights

**Comment by zaleslaw** [comment]
@Jolanrensen how do you estimate this code?

For me, it looks like a strange 2-3 level repeating function s with recursive call.

If it's a common pattern to apply changes in the dataframe, could you advise how to interpret correctly the code?

```

public fun <T> DataFrame<T>.renameToCamelCase(): DataFrame<T> {
    return rename {
        dfs { it.isColumnGroup() && it.name() matches DELIMITED_STRING_REGEX }
    }.toCamelCase()
        .rename {
            dfs { !it.isColumnGroup() && it.name() matches DELIMITED_STRING_REGEX }
        }.toCamelCase()
        .update {
            dfsOf<AnyFrame>()
        }.with { it.renameToCamelCase() }
}
```

**Comment by Jolanrensen** [comment]
@zaleslaw 
It's strange actually, the first two statements seem to be useless but I cannot merge them into 1.
 
It says:
First, recursively rename all column groups to camel case, 
then recursively rename all other columns to camel case, 
then finally, take all frame columns and call `renameToCamelCase()` on all dataframes inside.

It might look clearer after my rename:
```kotlin
public fun <T> DataFrame<T>.renameToCamelCase(): DataFrame<T> =
    rename {
        cols { it.isColumnGroup() && it.name() matches DELIMITED_STRING_REGEX }.recursively()
    }.toCamelCase()

    .rename {
        cols { !it.isColumnGroup() && it.name() matches DELIMITED_STRING_REGEX }.recursively()
    }.toCamelCase()

    .update {
        colsOf<AnyFrame>().recursively()
    }.with { it.renameToCamelCase() }
```
