### ISSUE TITLE
Project takes too much RAM to build

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#313]
`org.gradle.jvmargs=-Xmx8G` was introduced as a workaround because one of the tests didn't pass with OOM exception, but it would be nice to find out why and reduce xmx to a reasonable value, like 2 gb? For me even with 32 gb of ram it's painful to build dataframe with couple of opened projects and browser

**Comment by zaleslaw** [comment]
Test name in studio!

**Comment by zaleslaw** [comment]
I suggest sharing in this issue our ideas what could be a memory consumer and also ideas how to proof it with profiler or something else

**Comment by pacher** [comment]
On a related note, files like `DataFrameTests.kt` with 2.5k lines sometimes brings my not-the-newest-laptop to the knees when opened in Idea.
