### ISSUE TITLE
Make method declaration for four APIs more consistent 

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/dataframe#315]
- [x] Be sure that all methods are ordered by the same order (all, ColumnSelector, String, Reference, KProperties)
- [x] Be sure that there are no missed APIs
- [x] Reformat the code
- [x] Add spaces correctly between functions
- [x] add some docs if new method was added or removed

**Comment by Jolanrensen** [comment]
We can probably add the ColumnSelectionDsl to this list: https://kotlin.github.io/dataframe/columnselectors.html as it doesn't support KPoperties except in some select places:

```kotlin
df.select { it[Person::name] } // works
df.select { Person::name }

// by column path
df.select { it[Person::name][Name::firstName] } // works
df.select { Person::name[Name::firstName] }

// with a new name
df.select { Person::name named "Full Name" }

// converted
df.select { Person::name[Name::firstName].map { it.lowercase() } }

// column arithmetics
df.select { 2021 - Person::age }

// two columns
df.select { Person::name and Person::age } // works

// range of columns
df.select { Person::name..Person::age }

// all children of ColumnGroup
df.select { Person::name.all() }

// dfs traversal of all children columns
df.select { Person::name.allDfs() }
```
