### ISSUE TITLE
Order properties which are present in class primary constructor

### ISSUE THREAD

**Issue by ileasile** [Kotlin/dataframe#32]
We cannot infer the properties order in RT for this class:
```kotlin
class A {
    val x: Int
    val b: String
}
```

But we can do it for this class:
```kotlin
data class B(val x: Int, val b: String)
```

To achieve this, we may list primary constructor arguments names and map they to properties names:
```kotlin
KClass<*>.primaryConstructor?.parameters?.map { it.name }
```

**Comment by buckler4** [comment]
@ileasile - agreed this enhancement would be great for `toDataFrameByProperties`.  Additionally, I couldn't find a simple move method to order all the columns at once.
