### ISSUE TITLE
Rename dfs function

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#333]
When I first read 
```kotlin
df.select { dfsOf<Type> { it.size() > 10 } }
```
I thought it meant "Select dataframes of given type where their size is larger than 10".
Asking a friend of mine, they recognized "dfs" as "depth first search" but then they assumed it would return the deepest nested column, since a search is done when a result is found.

Plus, since this function traverses all column groups, it could just as well have been named bfs (breadth first search) and give the same result.

Clearly, this function needs renaming to avoid further confusion.

The functions that need to be renamed include `dfs {}`, `dfsOf<> {}` and `allDfs(includeGroups: Boolean)`. Plus, in the internal parts of the library, the name DFS is also sometimes used to just mean a "recursive flattening" of columns, which is definitely not a "search".

Candidates for a rename include:
```kotlin
df.select { traversingGroups { it.size() > 10 } }
df.select { traversingGroupsColsOf<Type> { it.size() > 10 } } // ??
df.select { allTraversingGroups(includeGroups = false) } // ?
```
or
```kotlin
df.select { cols(traversingGroups = true) { it.size() > 10 } }
df.select { colsOf<Type>(traversingGroups = true) { it.size() > 10 } }
df.select { all(traversingGroups = false, includeGroups = true) } // ?
```
or
```kotlin
df.select { allLevels { it.size() > 10 } }
df.select { allLevelsOf<Type> { it.size() > 10 } } // ?
df.select { allLevels(includeGroups = false) } // ?
```

Other ideas are welcome :)

**Comment by pacher** [comment]
Plus many. I thought the same thing, dfs = dataframes so probably something to do with frame columns. And I was always thinking "if only there would be a way to get all the columns recursively from all the nested groups". I was doing some workarounds and planning to try to implement it at some point and make a PR.
Until I finally saw "depth first search" mentioned once somewhere in the docs at the bottom of the page.
But now that I know it, it is hard to beet the name `dfs` in conciseness. And I use it quite a lot, so every letter counts. Having `traversingGroups` everywhere would look awful and be a big bummer for me.

What would help is a dedicated page in the docs visible in the index tree or a more prominent section with the words "traverse" or "recursive". I would certainly remember that such functionality exists when reading the docs for the first time. But at that point `dfs` was mentioned only once in some table with other functions and I missed it.

**Comment by Jolanrensen** [comment]
deepCols etc. however makes the api less readable out loud which is one of the strengths of the Dataframe DSL.

I also came up with
select withinGroups (but that leaves out the top level), alsoInGroups, andInGroups, inGroupsToo, recursively.

**Comment by Jolanrensen** [comment]
And if possible
`select { cols { it.size() > 10 }.recursively() }`

**Comment by pacher** [comment]
What is the difference between `select { all() }` and `select { cols() }` ?

My point is that `all` or `allCols()` is the perfect name for `dfs()`. That what I would expect from `allXXX` functions, recursive behavior. Perhaps we could deprecate and re-purpose `all`. I know it is a breaking change, but that's why we are at 0.x.x
Then we can also have `allGroups()` in addition to `allCols()` etc. 

I also find `dfs()` and `allDfs()` a little bit confusing. Why can't we just have `includeGroups: Boolean` parameter in `dfs()`?  Or maybe even just drop `allDfs()`. Currently if the user want to select with condition, they have to use `dfs` and include `!it.isColumnGroup()` in their predicate anyway.

This and if we rename `allUntil/Before/After/Since` will allow us to use `all` uniformly across the api to indicate recursive operations.

**Comment by Jolanrensen** [comment]
Working on it in https://github.com/Kotlin/dataframe/tree/dfs-rename
The basics work, along with `@Deprecation` annotations. However, some tests seem to fail due to changed orders.

**Comment by pacher** [comment]
How about going one level higher? I mean, we could have different top-level functions, like `selectAll {}` or `deepSelect {}` or even `selectRecursively {}`, although I really don't like the last one. The point is to change the meaning of the functions depending on the context, like `select { all() }` will select all top level but `deepSelect { all() }` or  `select { recursive { all() } }` to select all recursively. We can have a separate DSL for deep selections.

Just brainstorming, did not use it enough yet to really get an idea of what is better.

But I wanted to say that I do really like and fully embrace the hierarchical nature of kdf. So almost all of my columns are neatly organized in nested groups and I use recursive selectors most of the time. They do tend to get rather big though and `.recursively(includeGroups = false)` all over the place scares me a bit. It does look good as an API design, but I am trying to find a more concise way.

I am already used to `dfs` and it is very short. Do we need to remove it or can we keep it for "backwards compatibility" ;-) and have both?

**Comment by Jolanrensen** [comment]
Hmm, a level higher will probably be a bit too much, plus, since we have so many functions, hard to maintain.
We could probably also make an overload for `.rec()` or something short if it's used often, but probably `dfs` will have to go. It won't be immediate of course :) `@Deprecated` with level Warning and ReplaceWith etc.

**Comment by pacher** [comment]
Currently it is easy to write own recursive helper extensions, for example
```kotlin
fun <T> DataFrame<T>.deepSelectGroups(predicate: (ColumnGroup<*>) -> Boolean) =
    select { dfs { it.isColumnGroup() && predicate(it.asColumnGroup()) } }
```
I hope it will be the same easy with your new query wrappers when they are finished.

**Comment by Jolanrensen** [comment]
Maybe we should also consider https://github.com/Kotlin/dataframe/issues/270

**Comment by nikitinas** [comment]
I vote for `.recursively()` modificator that can be applied to any columns selector.
```kotlin
select { cols { it.size() > 10 }.recursively() }
```

**Comment by Jolanrensen** [comment]
One note for `.recursively()`: It changes `cols {}` from taking `(AnyCol) -> Boolean` to taking `(ColumnWithPath<*>) -> Boolean` aka `ColumnFilter<*>`. Otherwise, you won't be able to reason with `depth` etc.
This doesn't make much difference in the `cols {}` API, however it does change exact equality, making:
`df.group { cols { it != name } }.into { "nameless" }` -> `df.group { cols { it.data != name } }.into { "nameless" }`

**Comment by koperagen** [comment]
also here parameter "dfs" https://kotlin.github.io/dataframe/reorder.html#reordercolumnsby

**Comment by Jolanrensen** [comment]
Reworking it from the ground up in https://github.com/Kotlin/dataframe/tree/dfs-rename2. This time I do modify ColumnSet to be able to transform the previous call in the chain before resolving the current. 
Essentially allowing modifiers on ColumnSet returning calls, such as "colsOf<Boolean>().recursively()"

**Comment by Jolanrensen** [comment]
https://github.com/Kotlin/dataframe/pull/363

**Comment by Jolanrensen** [comment]
Merged :) While it might be a bit more wordy in some cases, at least at every step it's clear what you're doing IMO, especially with which types of columns are included and which aren't. Let me know what you think!
Currently busy reworking the ColumnsSelectionDsl further.
