### ISSUE TITLE
Consider changing "diff" to "diff" and "diffOrNull"

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#339]
Right now diff can return null, but i'd argue that in some situations it's not desirable and people will write something like
`diff { } ?: defaultValue`
But it's not that obvious that diff returns null at all and personally i find out about it only after my code explodes 
So, i think diff should have value parameter `default` and return non-null, and then we introduce a special version `diffOrNull`
It can even be nicely deprecated, as we add a new parameter, so we don't silently break anything

**Comment by Jolanrensen** [comment]
I don't think that's much of an issue. I face the same with some of my functions in the Selection DSL. This auto-generated replacement code can be shortened back to a lambda using IDE hints anyways, and for people using other IDEs, where ReplaceWith doesn't even work, they have to fix the deprecations manually anyways.

**Comment by koperagen** [comment]
IDE quick fix for conversion to lambda is a good point, i didn't think about it. Well, in that case, i guess i'll fix it in this release
