### ISSUE TITLE
expose `DataFrameSchema` types

### ISSUE THREAD

**Issue by rizsotto** [Kotlin/dataframe#36]
Hey there, thanks for this project. It looks very much I was looking for.

The feature I'm looking for is to query the schema of a `DataFrame`. This I need for to convert the `DataFrame` to a `LeapFrame` (which is a dataframe in MLeap project) to create input to an ML model. The `LeapFrame` represents the columns schema with it's own type, which basically a `name` and `type` tuple. The `type` is represented as `DataType`, which is a compound of `isNullable: Bool` and the `DataShape` which is either a `Scalar`, `Tensor` or `List` and `BasicType` which is one of `Int`, `Long`, `Double`, `String`, etc...

I was looking at the `DataFrameSchema` which is a good approximation of the `LeapFrame` schema. The only problem, that Kotlin type is part of the `internal` package, and not public. Would that be possible to make the `DataFrameSchema` (and the related types) available on the public API?

**Comment by koperagen** [comment]
Hi, thanks for sharing your use case! `DataFrameSchema` and related classes are now public in `org.jetbrains.kotlinx.dataframe.schema` package.
