### ISSUE TITLE
K2 front end compiler plugin ideas

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#381]
While for
```kotlin
@DataSchema
interface A
```
for accessor generation and schema recognition
```kotlin
@DataSchema
interface B1 {
    val a1: List<A>
    val a2: A
}
```
and 
```kotlin
@DataSchema
interface B2 {
    val a1: Dataframe<A>
    val a2: DataRow<A>
}
```
are similar. This is not the case when writing functions using the KProperties API.
For instance, taking the function 
```kotlin
public fun <C, R> KProperty<DataRow<C>>.select(selector: ColumnsSelector<C, R>): ColumnSet<R>
```
Then 
```kotlin
b1DataFrame.update { a2.select { /* does not work */ } }
b2DataFrame.update { a2.select { /* works */ } }
```

Of course, we can erase the type from the function like:
```kotlin
public fun <R> KProperty<*>.select(selector: ColumnsSelector<*, R>): ColumnSet<R>
```
but then we miss out on vital typing information, preventing the generated accessors from working etc. Plus, both overloads cannot coexist, unfortunately.

This could be solved in a front-end plugin by changing the types of the interface on the fly.

Alternatively, we could add extra typing restrictions based on the `@DataSchema` annotation, similar to [`@Positive` and `@Negative`](https://youtu.be/Pl-89n9wDqo?t=415), where some functions could be hidden or throw errors when called using a non-DataSchema annotated type.

**Comment by koperagen** [comment]
Your example uses dataschema api, not kproperties api, doesn't it? It should work for dataschema API, because the return type of `a2` extension is `DataRow`. And i think that's good enough. There's no reason to use kproperties api with `@DataSchema`

**Comment by Jolanrensen** [comment]
That's actually a good point
