### ISSUE TITLE
Tag version 0.11.0 has no release?

### ISSUE THREAD

**Issue by seljabali** [Kotlin/dataframe#415]
Hi team,

Thanks for the great work! Huge fan.

I've noticed there's a v0.11.0 [tag](https://github.com/Kotlin/dataframe/tags) but no matching release under [releases](https://github.com/Kotlin/dataframe/releases). Was v0.11 tag was accidentally made, if not, why doesn't it have release notes?

**Comment by seljabali** [comment]
https://github.com/Kotlin/dataframe/releases/tag/build-0.11.0 release was just made, and I see it points to the v0.11 tag. Perhaps then update the Release to include the version as with the rest please? Thanks team!

**Comment by zaleslaw** [comment]
Good idea, will rename, thanks for the attention, and yes, we have a gap, because need to a test some things before publish releases
