### ISSUE TITLE
Migrate netflix and titanic examples to Kandy

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#437]

**Comment by zaleslaw** [comment]
@koperagen could you please clarify the issue? Add links to the examples, motivation (why to do it), and what places should be changed (or added from scratch)

**Comment by koperagen** [comment]
Sure. These 2 notebooks use lets-plot for building plots, but now we also have Kandy. I think it will be nice to replace usages of lets-plot API with kandy api because it's intended to provide nicer Kotlin DSL
https://github.com/Kotlin/dataframe/tree/master/examples/notebooks/titanic
https://github.com/Kotlin/dataframe/tree/master/examples/notebooks/netflix

**Comment by zaleslaw** [comment]
@koperagen please, have a look, seems, like it's not actual anymore and I could close it

**Comment by Jolanrensen** [comment]
Actually, it was fixed in https://github.com/Kotlin/dataframe/pull/548
