### ISSUE TITLE
Static HTML output for dataframes in the Notebook for rendering on GitHub

### ISSUE THREAD

**Issue by ileasile** [Kotlin/dataframe#476]
Now DataFrame tables are not rendered in the notebooks when these notebooks are placed on GitHub. We could change it with the [approach](https://github.com/Kotlin/kandy/pull/155/files#diff-3aaadf3300c1cde75007e0241f7d11cfc13450d09ce493a7eb1afbd20c6cfeddR54-R61) used in Kandy library.

**Comment by zaleslaw** [comment]
We need fixed Notebooks examples

**Comment by Jolanrensen** [comment]
The current fix only works when notebooks are rendered in Jupyter Web, not in Kotlin Notebooks, because those are wrapped in an iFrame.
