### ISSUE TITLE
Fix @Deprecations for 0.12.1

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#477]
It looks like due to an error in the RELEASE_CHECK_LIST deprecations were migrated before the 0.12 release instead of afterward (when the master branch started to target 0.13).
I already made a PR to fix the order in the checklist: https://github.com/Kotlin/dataframe/pull/475
Now the deprecations need to be fixed across the library such that functions that are supposed to be WARNING in 0.12 are WARNING and those that are supposed to be ERROR are error (and removed ones are returned as ERROR).

**Comment by zaleslaw** [comment]
I've created a milestone for 0.12.1 to track all planned activities for the next release

**Comment by Jolanrensen** [comment]
Fixed in 0.12.1 branch, commit: https://github.com/Kotlin/dataframe/commit/34dcde032305c09c045b561a14d593d7e44311dd

**Comment by Jolanrensen** [comment]
And fixed for 0.13 in the master, commit: https://github.com/Kotlin/dataframe/commit/694a8e5adc062d0893a42a32d0a5cea0de587a8b
