### ISSUE TITLE
`skipLines` with `colTypes` not works as expected

### ISSUE THREAD

**Issue by nicolasfara** [Kotlin/dataframe#482]
I have a CSV file where the first 9 lines represent the header of the file.
Since those lines are not valid CSV rows, I want to read the CSV file skipping those lines.

To do so I have used the following code:

```kotlin
val header = listOf(
    "time", "canOffload[sum]", "wantToOffload[sum]", "effectiveLoad[mean]", "effectiveLoad[max]",
    "effectiveLoad[min]", "latency[mean]", "latency[max]", "latency[min]",
)
val colTypes = mapOf(
    "time" to ColType.Double,
    "canOffload[sum]" to ColType.Int,
    "wantToOffload[sum]" to ColType.Int,
    "effectiveLoad[mean]" to ColType.Double,
    "effectiveLoad[max]" to ColType.Double,
    "effectiveLoad[min]" to ColType.Double,
    "latency[mean]" to ColType.Double,
    "latency[max]" to ColType.Double,
    "latency[min]" to ColType.Double,
)

DataFrame.readCSV(
    it.toFile(),
    delimiter = ' ',
    skipLines = 9,
    header = header,
    colTypes = colTypes,
)
```

However, if I specify `colTypes` in order to specify the exact type for each col, the CSV is parsed from the first line even if I have specified the `skipLines = 9`.

The exception:
```
Couldn't parse '#####################################################################' into type kotlin.Double
```

where `#####################################################################` is the first line.

Without `colTypes` the dataframe is loaded correctly without the first 9 lines.

I expect that if I use `skipLines`, then also the parsing starts from the skipped lines and not from the first line.

**Comment by koperagen** [comment]
Hi! I tried to reproduce the problem, does this file look similar to what you have?
![image](https://github.com/Kotlin/dataframe/assets/12936457/cf8c0daf-833f-4fae-84e7-2bc8d9461b36)


From the sources i don't see obvious connections between `colTypes` and `skipLines`. One thing that i suspect is that you explicitly provide `header`. Then you have to skip header + one more line for names. Maybe you can provide a minimal repro file without sensitive data?

**Comment by nicolasfara** [comment]
Hi @koperagen I figured out there was a problem with the CSV: the `###########` characters are also at the end, which is why the parsing was failing.

Sorry for the noise

**Comment by koperagen** [comment]
No problems, glad to help :)
