### ISSUE TITLE
"What this page helpful?" broken

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#485]
Below each documentation page, there's this button:
![image](https://github.com/Kotlin/dataframe/assets/17594275/d4a8b08a-959d-44ed-b149-e610432ba65d)
which does not function:
![image](https://github.com/Kotlin/dataframe/assets/17594275/7e665940-d014-43be-a859-10916fea3efd)
with a non-working ticket creation button:
https://kotlin.github.io/dataframe/null

**Comment by zaleslaw** [comment]
Vote for removal
