### ISSUE TITLE
The method readSqlTable(connection, "table") returns different subsets of the table

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/dataframe#494]
From @Jolanrensen 

> Interestingly enough, running readSqlTable(connection, "table") with limit multiple times results in a different subset of the database. (if my first call had a limit of 100, the next time I call it it results in [100..200], then [200..300] and so on. This is again unexpected. This does not happen when running it from the console.

My comment: cursor issues

**Important to add tests for repeated calls**

**Comment by Jolanrensen** [comment]
I cannot reproduce it myself anymore, but it's good to have a test present if it ever occurs again
