### ISSUE TITLE
Bug: `DataFrame.readCSV("")` returns files in the folder

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#508]
![image_720](https://github.com/Kotlin/dataframe/assets/17594275/e7b8cdf1-4fa0-4dfd-b15e-29ca9bd1c92f)

Also happens with `readTSV` and other functions that use `catchHttpResonse`.
`readJson` crashes when trying to read it: `com.beust.klaxon.KlaxonException: Unexpected character at position 0: 'b' (ASCII: 98)'`, but this too should be caught.

**Comment by zaleslaw** [comment]
Could it be a default behavior for dplyr/pandas?

**Comment by Jolanrensen** [comment]
No, it makes no sense to display list the files in the directory and interpret that String as csv.
It should either throw an exception, or concatenate all CSVs in the directory and read them all :)

**Comment by Jolanrensen** [comment]
Will be solved in the new CSV implementation: "dataframe-csv"
