### ISSUE TITLE
Allow reading dataframe from an ArrowReader

### ISSUE THREAD

**Issue by fb64** [Kotlin/dataframe#528]
Some tools/frameworks like [datafustion](https://github.com/datafusion-contrib/datafusion-java) (java binding) or [duckdb](https://duckdb.org/docs/archive/0.9.2/api/java#arrow-export) does not directly expose inputstream of Arrow data but an ArrowReader. It could be useful and not so complicated to add `readArrowReader` method

**Comment by Jolanrensen** [comment]
Good idea! I'm not very familiar with Arrow, but it sounds like a reasonable addition. Comparable to reading from JDBC resultSets afaik.
I would suggest another name though, as you cannot really "read a reader". Maybe `readWithArrowReader` or `readUsingArrowReader`? And additionally an extension function `ArrowReader.toDataFrame()` for better discoverability.

I do have one concern. Can you read multiple times from the same `ArrowReader` instance or not? DataFrame is functional in the sense that the same input always yields the same output. This also holds for data sources. Things might become unexpected if reading multiple times from the same reader yields different results.

**Comment by Jolanrensen** [comment]
Actually `DataFrame.readArrow(ArrowReader)` could probably work even better

**Comment by fb64** [comment]
Ok for `DataFrame.readArrow(ArrowReader)`
I think  `ArrowReader` should be read only once like `InputStream` it's maybe different for [ArrowFileReader](https://arrow.apache.org/docs/java/reference/org/apache/arrow/vector/ipc/ArrowFileReader.html) as it takes a [SeekableByteChannel](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SeekableByteChannel.html) as input. 
Should I add `ArrowReader.toDataFrame()` extenstion in `arrowReading.kt` file too ? Maybe I can detect if a reader has be already read and throw an exception or return an error. I think it's the same case for `InputStream` generally it's only read once ....

**Comment by Jolanrensen** [comment]
It's indeed the same for `InputStream` good point.

Yes, please put the extension there. Most of our extensions are currently in :core, but since this is an optional supported type, :core cannot depend on it. 

I think an exception is a good way to go.

Would it also be possible to create some tests?

**Comment by fb64** [comment]
While I added some test I discover that write or read from ArrowIPC change the type of inner column. 
The following test fail  because c column is a LinkedHashMap on excepted Dataframe and an Arraylist on readIpc object
May I should create a specific issue for that ....

```kotlin
    @Test
    fun testReadIPC(){
        val a by columnOf("one")
        val b by columnOf(2.0)
        val c by listOf(
            mapOf(
                "c1" to Text("inner"),
                "c2" to 4.0,
                "c3" to 50.0,
            ) as Map<String, Any?>
        ).toColumn()
        val d by columnOf("four")
        val expected =  dataFrameOf(a, b, c, d)
        val readIpc = DataFrame.readArrowIPC(expected.saveArrowIPCToByteArray())
        readIpc shouldBe expected
    }
```

![image](https://github.com/Kotlin/dataframe/assets/3306862/1da1602e-bf54-4fc8-a860-b513ef62d2de)

![image](https://github.com/Kotlin/dataframe/assets/3306862/38b6986b-2344-46ee-b08f-2fc43732531b)

**Comment by fb64** [comment]
Extension and tests have been added but unfortunately it's complicated to detect if an ArrowReader has already be read (or could be once again) as no method exists and the underlying used source (InputStream, Channel, SeekableReadChannel...) is not accessible.

**Comment by fb64** [comment]
By the way, an Exception is already thrown (the type of exception dependis of the underlying source) if we try to re-read the Arrow Reader. I don't think that catch and rethrow another exception could be relevant.
