### ISSUE TITLE
:core:processKDocsMain task failing on Windows

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#544]
```
Execution failed for task ':core:processKDocsMain'. java.nio.file.InvalidPathException: Illegal char <
> at index 32: C:\Program Files\Git\cmd\git.exe
C:\Program Files\Git\bin\git.exe
```
@Jolanrensen I think you said it required fix from Gradle Git plugin. Can you check if it can be fixed now?

**Comment by Jolanrensen** [comment]
Should have been fixed by https://github.com/Kotlin/dataframe/commit/733ae6337ea868f0287e9abca3b9d077e66c1aee. Can you confirm this issue still appears when simple-git is v 2.0.3+?

**Comment by koperagen** [comment]
Build failed on TeamCity. I believe it was on a branch with most recent changes. Sadly, it was deleted already :(

**Comment by Jolanrensen** [comment]
I'll close it until it is reproduced
