### ISSUE TITLE
The `split` operation documentation contains the example for another operations `merge`

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/dataframe#562]
https://kotlin.github.io/dataframe/split.html#split-horizontally

<img width="753" alt="image" src="https://github.com/Kotlin/dataframe/assets/19648120/118194b7-5b2d-4067-af4c-85107716fce7">

NOTE: it should be deleted

**Comment by Jolanrensen** [comment]
Also, the `limit =` argument does not exist on the site

**Comment by Jolanrensen** [comment]
After investigation: it's not incorrect. The documentation just shows how the merged df is created before showing how it can be deconstructed again using Regex. That said, since users can now see the input DF, we can probably remove the first step for clarity.
