### ISSUE TITLE
WriteExcel sheets support

### ISSUE THREAD

**Issue by raudonikis** [Kotlin/dataframe#578]
Hi, looks like there is an issue with the sheet functionality for excel files, unless I am missing something. Writing to the same excel file with different sheet names (I would expect that new sheets would be created) simply overrides the previous sheet. Is there any way to add sheets to an already existing excel file? Or at least add columns to an already existing file?
This is what I've tried:

```kotlin
dataFrame.writeExcel(filePath, sheetName = "results")
anotherDataFrame.writeExcel(filePath, sheetName = "more results")
```

I am using version `0.12.1`.

**Comment by koperagen** [comment]
New flag on `0.13.0-dev-2801` should do the trick. 
```
dataFrame.writeExcel(filePath, sheetName = "results")
anotherDataFrame.writeExcel(filePath, sheetName = "more results", keepFile = true)
```

> I would expect that new sheets would be created

Interesting point about default behavior. Maybe it should be like this, indeed

**Comment by raudonikis** [comment]
> New parameter on `0.13.0-dev-2801` should do the trick.

Yes, this works. Thank you so much!

**Comment by zaleslaw** [comment]
It was fixed
