### ISSUE TITLE
`joinWith` method is missing

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/dataframe#584]
I tried to use this: https://kotlin.github.io/dataframe/joinwith.html

But `joinWith` is unresolved.

```
Syntax Error: Unresolved reference: joinWith
```

**Comment by Jolanrensen** [comment]
![image](https://github.com/Kotlin/dataframe/assets/17594275/1850b4cb-c537-48a6-a9fa-198ba1f08651)
No it isn't. Can you share an example where it's unresolved?

**Comment by devcrocod** [comment]
```kotlin
val df1 = dataFrameOf(
    "A" to listOf("A0", "A1", "A2"),
    "B" to listOf("B0", "B1", "B2"),
    "index" to listOf("I0", "I1", "I2")
)

val df2 = dataFrameOf(
    "C" to listOf("C0", "C2", "C3"),
    "D" to listOf("D0", "D2", "D3"),
    "index" to listOf("I0", "I2", "I3")
)

df1.joinWith(df2, type = JoinType.Full) { true }
```

I'm working in Datalore

**Comment by devcrocod** [comment]
Okay, seems on Datalore has old version of dataframe

**Comment by Jolanrensen** [comment]
Can reproduce it on Datalore. You're right.
`%useLatestDescriptors` fixes it there.

**Comment by zaleslaw** [comment]
@Jolanrensen what version has the Datalore?

**Comment by devcrocod** [comment]
The Datalore for new notebooks uses 
```
Name: kotlin-jupyter-kernel
Version: 0.11.0.377
```
according to the dataframe of the version that comes with this kernel.
