### ISSUE TITLE
Update Kover to 0.7.6

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#594]
The project uses `org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin:0.6.1` but it requires more work to update it to 0.7.0: https://github.com/Kotlin/kotlinx-kover/blob/v0.7.0/docs/gradle-plugin/migrations/migration-to-0.7.0.md

**Comment by fb64** [comment]
I think this one can be closed
