### ISSUE TITLE
Incorrect permission setting for the pre-commit file

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/dataframe#612]
After cloning the repository and trying to make local changes, I encountered a problem executing a commit due to limited access rights to the pre-commit file. This results in a `Permission denied` error and I can't commit:
```
13:02:59.977: [dataframe] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/DataFrameReadTest.kt core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/RenderingTests.kt core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterHtmlRenderer.kt core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt build.gradle.kts
13:02:59.988: [dataframe] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /private/var/folders/h_/ln1cbg0j01vdr_636gjcr1wc0000kt/T/git-commit-msg-.txt --
/bin/sh: .git/hooks/pre-commit: Permission denied
```

IDEA: IU-242.1737
macOS: 14.2.1 (23C71)
git version 2.39.3 (Apple Git-145)

**Comment by Jolanrensen** [comment]
Probably, setting the permissions is done differently on MacOS.

This is the function that creates the pre-commit file:
```kts
// This task installs the pre-commit hook to the local machine the first time the project is built
// The pre-commit hook contains the command to run processKDocsMain before each commit
val installGitPreCommitHook by tasks.creating(Copy::class) {
    doNotTrackState(/* reasonNotToTrackState = */ "Fails on TeamCity otherwise.")

    val gitHooksDir = File(rootProject.rootDir, ".git/hooks")
    if (gitHooksDir.exists()) {
        from(File(rootProject.rootDir, "gradle/scripts/pre-commit"))
        into(gitHooksDir)
        fileMode = 755
    } else {
        logger.lifecycle("'.git/hooks' directory not found. Skipping installation of pre-commit hook.")
    }
}
```

Could you try setting the permissions manually?

**Comment by devcrocod** [comment]
Even if I run `.gradlew` through the terminal with `sudo`, I still get a file like this: `--wxrw--wx   1 Pavel.Gorgulov  staff   156B Mar  4 13:51 pre-commit`

**Comment by Jolanrensen** [comment]
so... looks like `fileMode` doesn't work as expected on MacOS

**Comment by Jolanrensen** [comment]
@devcrocod can you try `fileMode = 0b1011110011`

**Comment by devcrocod** [comment]
It didn't help(

**Comment by devcrocod** [comment]
Oh, if I remove `fileMode` then the following permissions are set: `-rw-r--r--   1 Pavel.Gorgulov  staff   156B Mar  5 14:23 pre-commit`

**Comment by Jolanrensen** [comment]
yeah, it needs execute permission, so something like -rwx-r-xr-x, which, if my math is correct is 755

**Comment by Jolanrensen** [comment]
Can be reproduced on Linux sometimes too.

**Comment by phanlezz** [comment]
> It didn't help( @Jolanrensen 

> @devcrocod can you try `fileMode = 0b1011110011` 

For us `0b111101101` worked :) so a literal translation of 7-5-5
