### ISSUE TITLE
[Feature Request] Read from database and automatically cast to camel case

### ISSUE THREAD

**Issue by dragove** [Kotlin/dataframe#624]
Most of the developers use sneak case in database systems but use camel case in java or kotlin source code.

I hope if there is a convenient way to do auto cast when read data from database.

e.g. if a table has these properties

```sql
create table demo(
  id int,
  first_name text,
  last_name text
)
```

after using `val df = DataFrame.readSqlTable(config, "demo", 10, caseConvertor=Convertors.sneakToCamelConvertor)` we can access property with camel case `df.firstName[0]`

**Comment by amandelpie** [comment]
Good suggestion, thanks

**Comment by Jolanrensen** [comment]
While we cannot do it on read atm, we do have the `DataFrame<T>.renameToCamelCase()` function. This will also convert snake case to camelCase automatically

**Comment by dragove** [comment]
Thanks, this worked for me.

Please close this issue if this is one is not planed since it's not important. Or remain this issue if it's worth to implement. Thanks again.
