### ISSUE TITLE
Enable use of other ArrowReader implementations

### ISSUE THREAD

**Issue by fb64** [Kotlin/dataframe#627]
Some librairies or framework (DuckDB for example) rely on [ArrowArrayStreamReader](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/ArrowArrayStreamReader.java) to share Arrow data. It would be nice to be more permissive and let any implementation of any ArrowReader works for reading arrow data

**Comment by Jolanrensen** [comment]
Sounds like a good idea! We might need a test with an `ArrowArrayStreamReader` though, to make sure it works as expected.

**Comment by fb64** [comment]
I finally added a test with DuckDB that uses `ArrowArrayStreamReader`
