### ISSUE TITLE
Update extension properties API docs

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/dataframe#635]
I think there needs to be more explanation and examples here, topic looks seriously incomplete:
https://kotlin.github.io/dataframe/extensionpropertiesapi.html

**Comment by Jolanrensen** [comment]
What else would you want to be there? Some example of what is generated perhaps?
There is already more at:
https://kotlin.github.io/dataframe/schemasgradle.html#execute-the-assemble-task-to-generate-type-safe-accessors-for-schemas

**Comment by AndreiKingsley** [comment]
No, I don't want implementation details or other deep stuff. I'd like users, unfamiliar with DataFrame, to have a clearer understanding. For example, to say that "in this cell a dataframe appeared, it has these columns, and we can use them further like that".
So, in my personal opinion, there seems to be a lack of clarity regarding what happened between the lines of code.
