### ISSUE TITLE
K2

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/dataframe#649]
Is there any branch or PR working on a K2 update? I started working on this and it seems like a heavy task so I'm wondering if anyone else has started.

**Comment by koperagen** [comment]
We'll update KSP plugin  and it should be enough for library users to use dataframe in their K2 builds as a dependency. As for updating to K2 compiler in our project itself, no one has started working on it yet.

**Comment by Jolanrensen** [comment]
There's also the [Jupyter](https://github.com/Kotlin/kotlin-jupyter/tree/master) dependency. Atm Jupyter tests don't run if we compile the integration classes with Kotlin 2.0. I hope this will work once it is not in preview anymore, but I'm not sure.

**Comment by Jolanrensen** [comment]
It's important to note that DataFrame will likely work fine as a library in your Kotlin 2.0+ project btw, as Kotlin is inherently backwards compatible.

**Comment by jsjeon** [comment]
I'd like to point out: https://youtrack.jetbrains.com/issue/KT-65676/K2-type-checking-has-run-into-a-recursive-problem-for-property-with-same-name-as-class-on-classpath#focus=Comments-27-9726934.0-0

**Comment by Jolanrensen** [comment]
A small fix regarding this was merged [here](https://github.com/Kotlin/dataframe/pull/665).
More fixes are on the way here: https://github.com/Kotlin/dataframe/pull/708

**Comment by Jolanrensen** [comment]
One final thing that currently stops us to update is our outdated linter:
https://github.com/Kotlin/dataframe/issues/364
It officially only supports Kotlin up to 1.4 or something... Well it finally broke at 2.0.

**Comment by Kantis** [comment]
It seems possible to use K2 and Dataframe 0.13 together. You need to force KSP to a K2 compatible version and apply the KSP gradle plugin yourself.

```kotlin
// in build.gradle.kts
plugins {
   id("org.jetbrains.kotlinx.dataframe") version "0.13.1"
   id("com.google.devtools.ksp") version "2.0.0-1.0.21"
}

// in /settings.gradle.kts
buildscript {
   configurations.all {
      resolutionStrategy {
         force("com.google.devtools.ksp:symbol-processing-api:2.0.0-1.0.21")
         force("com.google.devtools.ksp:symbol-processing-gradle-plugin:2.0.0-1.0.21")
      }
   }
}
```

Disclaimer: Not sure if this might cause unexpected issues. My builds are passing though.

**Comment by Jolanrensen** [comment]
@Kantis Nice! You could probably even skip the `force()` with setting `kotlin.dataframe.add.ksp=false`, like [here](https://github.com/Kotlin/dataframe/blob/76091c77b99eaa91d0f4d3da87debfc3f820ec8b/gradle.properties#L13).
