### ISSUE TITLE
Reading CSV with byte order mark bleeds into first Column Name

### ISSUE THREAD

**Issue by janseeger** [Kotlin/dataframe#687]
If you try to read a CSV file that begins with a BOM, the first column name will be all weird.

<img width="122" alt="Screenshot 2024-05-05 at 20 20 56" src="https://github.com/Kotlin/dataframe/assets/1467318/9603741b-043f-4f1f-a959-b87848f77f8a">

**Comment by Jolanrensen** [comment]
Do you have a sample CSV so we can make some tests too?

**Comment by janseeger** [comment]
Unfortunately none that I can easily share. I'll try to create a small reproducer this evening.

**Comment by janseeger** [comment]
Here's the [CSV File](https://github.com/Kotlin/dataframe/files/15234290/with-bom.csv). I noticed that the Column Names are correct when accessed with `columnNames()` but the generated code does not strip the BOM character.

<img width="584" alt="Screenshot 2024-05-07 at 12 37 21" src="https://github.com/Kotlin/dataframe/assets/1467318/73756a1c-55ee-4ccb-a2b2-03ab13daf7e1">

**Comment by Jolanrensen** [comment]
Can reproduce, thanks :) Looks like the column name is read incorrectly entirely, since getting by name (without zero width non breaking space character) also breaks.

![image](https://github.com/Kotlin/dataframe/assets/17594275/7cc3cd32-002a-4330-9d7e-a7788ffff097)
