### ISSUE TITLE
☂ `type: KType` in `DataColumnImpl` mismatches actual values sometimes

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#713]
`type: KType` in `DataColumnImpl` mismatches actual values in some cases. This can result in runtime exceptions and makes life difficult attempting to fix https://github.com/Kotlin/dataframe/issues/30 or https://github.com/Kotlin/dataframe/issues/704 where we assume the `type` always correctly represents the data.
This issue relates to https://github.com/Kotlin/dataframe/issues/701 as well.

To discover these bugs, we can introduce a (debug-only!!) check in `DataColumnImpl`, like:

```kt
private infix fun <T> T?.matches(type: KType) =
    when {
        this == null -> type.isMarkedNullable
        this.isPrimitiveArray -> type.isPrimitiveArray &&
            this!!::class.qualifiedName == type.classifier?.let { (it as KClass<*>).qualifiedName }

        this.isArray -> type.isArray // cannot check the precise type of array
        else -> this!!::class.isSubclassOf(type.classifier as KClass<*>)
    }

init {
    if (DEBUG) {
        require(values.all { it matches type }) {
            val types = values.map { if (it == null) "Nothing?" else it!!::class.simpleName }.distinct()
            "Values of column '$name' have types '$types' which are not compatible given with column type '$type'"
        }
    }
}
```
At the moment of testing, I can find 8+ breaking tests in `:core`:
- `org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest#aggregate by column`
  - data has types `[DataFrameImpl]`, `kType` is: `org.jetbrains.kotlinx.dataframe.aggregation.AggregateGroupedDsl<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType1>`
  - This exception is probably fine to ignore, as `AggregateGroupedDsl` is a `DataFrame`
- `org.jetbrains.kotlinx.dataframe.samples.api.Analyze#pivotDefault_accessors` / `#pivotDefault_strings` / `#pivotDefault_properties`
  - data has types `[Boolean, Int]`, `kType` is: `kotlin.Boolean`
  - Not really sure what's going on here, something with `concatImpl` I think
- `org.jetbrains.kotlinx.dataframe.samples.api.Modify#customConverters`
  - data has types `[Nothing?]`, `kType` is `kotlin.Int`
  - Seems to originate from `convertToImpl$convertToSchema`
- `org.jetbrains.kotlinx.dataframe.samples.api.Modify#implode`
  - data has types `[DataFrameImpl, Nothing?]`, `kType` is: `org.jetbrains.kotlinx.dataframe.DataFrame<*>`, not nullable
  - Seems to originate from `implodeImpl` where a `null` is put in a `FrameColumn`
- `org.jetbrains.kotlinx.dataframe.testSets.person.DataFrameTests#convertTo`
  - data has type: `[Nothing?]`, `kType` is: `kotlin.Int`
  - From `convertToImpl$convertToSchema` too
- `org.jetbrains.kotlinx.dataframe.testSets.person.DataFrameTreeTests#merge rows into table`
  - data has types `[DataFrameImpl, Nothing?]`, `kType` is: `org.jetbrains.kotlinx.dataframe.DataFrame<*>`, not nullable
  - Seems to originate from `implodeImpl` too where a `null` is put in a `FrameColumn`

Edit: running it afresh (clean pull of master with check) I get 15 failing tests.

There is also an exception in `:dataframe-jdbc`: https://github.com/Kotlin/dataframe/issues/701

**Comment by Jolanrensen** [comment]
7/15 tests are fixed by https://github.com/Kotlin/dataframe/issues/727

Next are the pivot tests with `0` and `true` in `Boolean` columns.
I suspect this is due to `default()` taking `Any?` and the pivot implementation not re-inferring the types of the columns after filling in a `null` with the given default in: `df.pivot { city }.groupBy { name }.default(0).min()`.

**Comment by Jolanrensen** [comment]
After merging https://github.com/Kotlin/dataframe/issues/713 there are just 5 failing tests left:
![image](https://github.com/Kotlin/dataframe/assets/17594275/dc5f95b3-ae2b-4961-a100-1175a0ed4659)

**Comment by Jolanrensen** [comment]
https://github.com/Kotlin/dataframe/pull/796 adds the ability to set `-Pkotlin.dataframe.debug=true` and run the checks for this issue :)

**Comment by Jolanrensen** [comment]
@zaleslaw After #796 is merged, I´d recommend running the JDBC tests again in debug mode. 

I now have 15 failing tests just from that module. They contain all sorts of Char/String, Double/Float, and Int/Short mismatches

**Comment by Jolanrensen** [comment]
One of the tests triggeres in `convertToImpl`. It seems like a temporary null-filled column is created even though the column type might be not-nullable. This needs a small workaround but probably would not have caused user-facing bugs

**Comment by zaleslaw** [comment]
Please, @Jolanrensen, create a ticket with the list of these JDBC tests, include in 0.14 milestone and assign on me

**Comment by Jolanrensen** [comment]
Attempt to work with `assert()` and the -ea JVM flag as it does the same :)

**Comment by Jolanrensen** [comment]
Debug mode is now enabled on TeamCity! Thanks for the help fixing the issues @zaleslaw :)
