### ISSUE TITLE
Bug in type inference

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#82]
It seems that the type of column named `value` is always `Any?` no matter the data. To reproduce, check out [this branch](https://github.com/Kotlin/dataframe/tree/type-inference-bug) or copy test from [latest commit](https://github.com/Kotlin/dataframe/commit/710da583c6eada4acc5962523e620856920098fe)

**Comment by Jolanrensen** [comment]
```kotlin
val df = DataFrame.readJsonStr(
    """
            {
              "key": "icon",
              "value": "str"
            }
        """.trimIndent()
)

df.print(columnTypes = true, title = true, borders = true)
println(df.schema().columns["value"]?.type)
// ⌌----------------------------⌍
// |  | key:String| value:String|
// |--|-----------|-------------|
// | 0|       icon|          str|
// ⌎----------------------------⌏
//
// kotlin.String
```
Seems to have been solved!
