### ISSUE TITLE
DataFrame.describe() Sortable by Type

### ISSUE THREAD

**Issue by jeffgnpc** [Kotlin/dataframe#822]
When I run df.describe() I would like to group columns of like types together.  When I try and click the sort button on the dataframe I get this error:
Column 'type' has type 'kotlin.Any' that is not Comparable java.lang.RuntimeException: Column 'type' has type 'kotlin.Any' that is not Comparable at org.jetbrains.kotlinx.dataframe.impl.columns.UtilsKt.assertIsComparable(Utils.kt:98) at org.jetbrains.kotlinx.dataframe.impl.api.SortKt.createComparator(sort.kt:60) at org.jetbrains.kotlinx.dataframe.impl.api.SortKt.sortByImpl(sort.kt:49) at

It would seem to me that sorting based on toString() when a Comparable is not available.  

I was able to get around the problem with this code:
```kt
df.describe().sortWith { r1, r2 -> r1["type"].toString().compareTo(r2["type"].toString()) }[0]["type"]
```

**Comment by Jolanrensen** [comment]
Thanks for letting us know! That seems like a bug indeed. I like the idea of sorting by String for non comparable columns too. We can do this in two different places though:
- on the notebook side 
  - keep `sortBy` in the library as is: fail when you're sorting a non-comparable column, but fallback to string sorting in the notebook, then the button work as expected
- on the library side
  - changes the behavior of dataframe, might be unexpected if some random type suddenly has order

**Comment by Jolanrensen** [comment]
@ermolenkodev is this something you would like to do from the notebook/table side?

**Comment by ermolenkodev** [comment]
It won’t work as a fallback on the KTNB plugin side because, in general, only a subset of rows is loaded for visualization. This could confuse users, as they might not realize that the sorting is applied only to the local subset of rows rather than the entire column’s values.
However, we can try to implement a fallback in the sorting command sent to the kernel for execution.
