### ISSUE TITLE
Library missing on maven-central

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/dataframe#85]
The readme states that the library is located under https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/dataframe/0.8.0-rc-5/dataframe (via `implementation 'org.jetbrains.kotlin:dataframe:0.8.0-rc-5'`).  But the library seems to be missing. In fact, it's not just the version but the entire path seems absent on central https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/dataframe/

**Comment by ileasile** [comment]
Hi, Holger! I think it's a mistake in Readme, correct path is
https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/dataframe/

**Comment by holgerbrandl** [comment]
Thanks for the corrected pointer.

**Comment by ileasile** [comment]
Fixed README
