### ISSUE TITLE
GH action "Build docs"->"Publish Indexes" fails

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#886]
https://github.com/Kotlin/dataframe/actions/runs/11031583430/job/30638690882

![image_720](https://github.com/user-attachments/assets/ebf39b14-6042-4d9c-9461-cd4e1d7218b2)

It fails both for v3 and v4, so it might have something to do with the algolia docker container

**Comment by koperagen** [comment]
Tasks uses ubuntu-latest. Likely it was something like ubuntu-20.04 previously which over time became 22.04 or some sort of dev build

**Comment by Jolanrensen** [comment]
hmm it seems to fail both for ubuntu-20.04 and 22.04

**Comment by Jolanrensen** [comment]
the search on the website is broken until we fix it :( so it's quite urgent

**Comment by Jolanrensen** [comment]
![image](https://github.com/user-attachments/assets/ef0ad512-51d9-4fff-ab9f-d18894cc072a)
