### ISSUE TITLE
Remove dependency on fuel

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#904]
There's exactly 1 usage of this library in catchHttpResponse method. I reckon it was used for cases when HTTP response is other than 200, so usual URL.readText won't work to parse response body. But apparently `URL.connection as HttpUrlConnection` opens a lot possibilities, including reading response body even in case of 404 errors
It'll save us ~300kb artifact size

**Comment by Jolanrensen** [comment]
I'll avoid it in https://github.com/Kotlin/dataframe/issues/827 :)

**Comment by koperagen** [comment]
Seems like it
