### ISSUE TITLE
`flatten` separator for `keepParentNameForColumns` should not be `.`

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#911]
Related to https://github.com/Kotlin/dataframe/issues/666

Since we're generating accessors for columns, having a `.` in a column name might cause unexpected behavior. (Such as column accessors with ``` `` ``` around their name). `_` might be a better default.

**Comment by zaleslaw** [comment]
Should we forbid a wide range of separators, or propose something from "white list" only? Let's answer ourselves

**Comment by Jolanrensen** [comment]
We should follow the kotlin spec:

- `(Letter | '_') {Letter | '_' | UnicodeDigit}` is allowed without `` ` ``
  - Letter: any unicode character of categories Lu, Ll, Lt, Lm or Lo
  - UnicodeDigit: any unicode character of category Nd
- ``'`' QuotedSymbol {QuotedSymbol} '`'``
  - any character excluding CR, LF and `` '`' `` (well except the last part, we cannot write `` ` `` inside a name with backticks
- `., ;, [, ], /, <, >, :, \\` are never allowed

Source: https://kotlinlang.org/spec/syntax-and-grammar.html#identifiers

That said, these never-allowed characters might appear from sources like csv/json, so I'm wondering whether we should replace them immediately or, like now, fix it only when generating accessors?

**Comment by koperagen** [comment]
I vote to keep name String as is and only replace characters in generated properties names. So, to not change this logic

**Comment by Jolanrensen** [comment]
> I vote to keep name String as is and only replace characters in generated properties names. So, to not change this logic

Alright, but can the generated property then always use `_` instead of ` `?

**Comment by koperagen** [comment]
I wouldn't want to change to `_`, `group col` looks cleaner than `group_col` imo. Completion even inserts backticks automatically when you type, you don't have to start with `.

**Comment by koperagen** [comment]
> > I wouldn't want to change to `_`, `group col` looks cleaner than `group_col` imo. Completion even inserts backticks automatically when you type, you don't have to start with `.
> 
> It works in notebooks in the IDE yes, but I don't know about other environments. Also I've got to disagree about cleaner looks:
> 
> * `df.parent_child`
> * `` df.`parent child` ``
> 
> I feel like backticks are a "last resort" in Kotlin. Like "okay you're not supposed to use this character, but if you really want to you can do it in backticks". If a space already exists in the name, then yes, we should just generate backticks around the name and call it a day. But I don't think we should explicitly introduce characters that need backticks to work.

I want to make it clear that i speak about ` ` in ValidFieldName, where invalid symbol is replaced by it
